### ISSUE TITLE
XSS in "Question Name"

### ISSUE THREAD

**Issue by DaKnOb** [grnet/zeus#29]
An XSS vulnerability exists in the `Question Name` field allowing an ill-intentioned administrator to execute arbitrary JavaScript code in viewers' browsers. More specifically you can test this problem by creating a vote with a question with name `<script>alert("XSS");</script>` and then review the votes. If everything works correctly the browser will show a popup window meaning the browser has executed the content provided by the administrator using the browser's JavaScript Engine.

Attached is a screenshot of a successful Content Spoofing Attack against the Demo Zeus deployed at https://zeus.grnet.gr/

![xss-zeus-2](https://cloud.githubusercontent.com/assets/743648/7614396/2cdda134-f99f-11e4-9d54-19a359f59aba.png)

**Comment by louridas** [comment]
The attack is feasible. It will be detectable because the bogus ballot will be shown as such when the votes are counted.

**Comment by DaKnOb** [comment]
This attack gives access to the voters' browsers and can force them to do whatever the attacker wants (click any option, etc.) and not show the victim the result (spoof content). 
Then, a sysadmin can change all the e-mails rendering the attack impossible to detect.

**Comment by louridas** [comment]
If the attacker manages to insert JS into the ballot, the JS will be visible when decrypted (because it is not decrypted via JS) and thus detectable.
